/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BasesAudioPlayerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var BasesAudioPlayerPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.observer = null;
    this.isProcessing = false;
  }
  async onload() {
    console.log("Loading Bases Audio Player Plugin");
    this.addStyles();
    this.app.workspace.onLayoutReady(() => {
      setTimeout(() => this.processAllCards(), 500);
      this.setupObserver();
    });
  }
  addStyles() {
    const styleEl = document.createElement("style");
    styleEl.id = "bases-audio-player-styles";
    styleEl.textContent = `
            /* Bases Audio Player Styles */
            
            /* Hover effect verbetering voor overlay button */
            .bases-audio-overlay .bases-audio-play-button:hover {
                opacity: 1 !important;
                transform: scale(1.15) !important;
            }
            
            /* Zorg dat de cover de overlay goed toont */
            .bases-cards-cover {
                position: relative;
                overflow: visible;
            }
            
            /* Optional: Semi-transparante achtergrond voor de hele cover bij hover */
            .bases-card:hover .bases-audio-overlay {
                background: radial-gradient(circle, rgba(0,0,0,0.3) 0%, transparent 70%);
            }
            
            /* Table view styling */
            .bases-audio-inline {
                display: inline-flex !important;
                align-items: center !important;
                gap: 8px !important;
            }
            
            .bases-audio-inline .bases-audio-play-button {
                width: 32px !important;
                height: 32px !important;
                font-size: 14px !important;
                background: var(--interactive-accent) !important;
                color: var(--text-on-accent) !important;
            }
            
            .bases-audio-inline .bases-audio-play-button:hover {
                opacity: 0.9 !important;
                transform: scale(1.1) !important;
            }
        `;
    document.head.appendChild(styleEl);
  }
  onunload() {
    console.log("Unloading Bases Audio Player Plugin");
    if (this.observer) {
      this.observer.disconnect();
    }
    const styleEl = document.getElementById("bases-audio-player-styles");
    if (styleEl) {
      styleEl.remove();
    }
  }
  setupObserver() {
    let timeout;
    this.observer = new MutationObserver((mutations) => {
      var _a, _b, _c, _d;
      let hasNewContent = false;
      for (const mutation of mutations) {
        for (const node of Array.from(mutation.addedNodes)) {
          if (node instanceof HTMLElement) {
            if (((_a = node.classList) == null ? void 0 : _a.contains("bases-cards-item")) || ((_b = node.querySelector) == null ? void 0 : _b.call(node, ".bases-cards-item")) || ((_c = node.classList) == null ? void 0 : _c.contains("bases-td")) || ((_d = node.querySelector) == null ? void 0 : _d.call(node, ".bases-td"))) {
              hasNewContent = true;
              break;
            }
          }
        }
        if (hasNewContent)
          break;
      }
      if (!hasNewContent)
        return;
      clearTimeout(timeout);
      timeout = setTimeout(() => {
        if (!this.isProcessing) {
          this.processAllCards();
        }
      }, 100);
    });
    this.observer.observe(document.body, {
      childList: true,
      subtree: true
    });
  }
  processAllCards() {
    if (this.isProcessing)
      return;
    this.isProcessing = true;
    if (this.observer) {
      this.observer.disconnect();
    }
    try {
      const audioExtensions = [".mp3", ".wav", ".ogg", ".m4a"];
      const cardItems = document.querySelectorAll(".bases-cards-item");
      cardItems.forEach((cardItem) => {
        const cover = cardItem.querySelector(".bases-cards-cover");
        if (!cover)
          return;
        const existingOverlay = cover.querySelector(".bases-audio-overlay");
        if (existingOverlay) {
          existingOverlay.remove();
        }
        const musicProperty = cardItem.querySelector('.bases-cards-property[data-property="note.Music"]');
        if (!musicProperty)
          return;
        const audioLink = musicProperty.querySelector("span.internal-link[data-href], div.metadata-link-inner.internal-link[data-href]");
        if (!audioLink)
          return;
        const dataHref = audioLink.getAttribute("data-href");
        if (!dataHref)
          return;
        const isAudioFile = audioExtensions.some(
          (ext) => dataHref.toLowerCase().endsWith(ext)
        );
        if (!isAudioFile)
          return;
        const fileName = audioLink.textContent || dataHref;
        let file = this.app.vault.getAbstractFileByPath(dataHref);
        if (!file) {
          const allFiles = this.app.vault.getFiles();
          file = allFiles.find((f) => f.name === dataHref || f.path.endsWith(dataHref)) || null;
        }
        if (!file) {
          if (musicProperty instanceof HTMLElement) {
            musicProperty.style.display = "none";
          }
          return;
        }
        if (cover instanceof HTMLElement) {
          cover.style.position = "relative";
        }
        if (musicProperty instanceof HTMLElement) {
          musicProperty.style.display = "none";
        }
        const overlay = this.createAudioOverlay(file, fileName);
        cover.appendChild(overlay);
      });
      const musicTds = document.querySelectorAll('.bases-td[data-property="note.Music"]');
      musicTds.forEach((td) => {
        const existingPlayer = td.querySelector(".bases-audio-inline");
        const audioLink = td.querySelector("div.metadata-link-inner.internal-link[data-href]");
        if (existingPlayer && !audioLink) {
          return;
        }
        if (existingPlayer && audioLink) {
          existingPlayer.remove();
        }
        if (!audioLink)
          return;
        const dataHref = audioLink.getAttribute("data-href");
        if (!dataHref)
          return;
        const isAudioFile = audioExtensions.some(
          (ext) => dataHref.toLowerCase().endsWith(ext)
        );
        if (!isAudioFile)
          return;
        const fileName = audioLink.textContent || dataHref;
        let file = this.app.vault.getAbstractFileByPath(dataHref);
        if (!file) {
          const allFiles = this.app.vault.getFiles();
          file = allFiles.find((f) => f.name === dataHref || f.path.endsWith(dataHref)) || null;
        }
        if (!file)
          return;
        const metadataLink = audioLink.closest(".metadata-link");
        if (!metadataLink || !metadataLink.parentElement)
          return;
        const inline = this.createAudioInline(file, fileName);
        metadataLink.parentElement.replaceChild(inline, metadataLink);
      });
    } finally {
      this.isProcessing = false;
      if (this.observer) {
        this.observer.observe(document.body, {
          childList: true,
          subtree: true
        });
      }
    }
  }
  createAudioOverlay(file, fileName) {
    const playIcon = `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg>`;
    const pauseIcon = `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="6" y="4" width="4" height="16"></rect><rect x="14" y="4" width="4" height="16"></rect></svg>`;
    const container = document.createElement("div");
    container.className = "bases-audio-overlay";
    container.style.cssText = `
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            z-index: 10;
        `;
    const audioPlayer = document.createElement("audio");
    audioPlayer.src = this.app.vault.adapter.getResourcePath(file.path);
    audioPlayer.style.display = "none";
    const playButton = document.createElement("button");
    playButton.className = "bases-audio-play-button";
    playButton.innerHTML = playIcon;
    playButton.style.cssText = `
            width: 48px;
            height: 48px;
            border-radius: 50%;
            border: none;
            background: rgba(0, 0, 0, 0.7);
            color: white;
            cursor: pointer;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 0;
            flex-shrink: 0;
            backdrop-filter: blur(8px);
            transition: all 0.2s ease;
        `;
    let isPlaying = false;
    playButton.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      if (isPlaying) {
        audioPlayer.pause();
        playButton.innerHTML = playIcon;
        isPlaying = false;
      } else {
        document.querySelectorAll(".bases-audio-overlay audio, .bases-audio-inline audio").forEach((audio) => {
          if (audio !== audioPlayer) {
            audio.pause();
          }
        });
        document.querySelectorAll(".bases-audio-play-button").forEach((btn) => {
          if (btn !== playButton) {
            btn.innerHTML = playIcon;
          }
        });
        audioPlayer.play();
        playButton.innerHTML = pauseIcon;
        isPlaying = true;
      }
    });
    audioPlayer.addEventListener("ended", () => {
      playButton.innerHTML = playIcon;
      isPlaying = false;
    });
    playButton.addEventListener("mouseenter", () => {
      playButton.style.transform = "scale(1.1)";
      playButton.style.background = "rgba(0, 0, 0, 0.85)";
    });
    playButton.addEventListener("mouseleave", () => {
      playButton.style.transform = "scale(1)";
      playButton.style.background = "rgba(0, 0, 0, 0.7)";
    });
    container.appendChild(audioPlayer);
    container.appendChild(playButton);
    return container;
  }
  createAudioInline(file, fileName) {
    const playIcon = `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg>`;
    const pauseIcon = `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="6" y="4" width="4" height="16"></rect><rect x="14" y="4" width="4" height="16"></rect></svg>`;
    const container = document.createElement("div");
    container.className = "bases-audio-inline";
    container.style.cssText = "display: inline-flex; align-items: center; gap: 8px;";
    const audioPlayer = document.createElement("audio");
    audioPlayer.src = this.app.vault.adapter.getResourcePath(file.path);
    audioPlayer.style.display = "none";
    const playButton = document.createElement("button");
    playButton.className = "bases-audio-play-button";
    playButton.innerHTML = playIcon;
    playButton.style.cssText = `
            width: 32px;
            height: 32px;
            border-radius: 50%;
            border: none;
            background: var(--interactive-accent);
            color: var(--text-on-accent);
            cursor: pointer;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 0;
            flex-shrink: 0;
        `;
    let isPlaying = false;
    playButton.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      if (isPlaying) {
        audioPlayer.pause();
        playButton.innerHTML = playIcon;
        isPlaying = false;
      } else {
        document.querySelectorAll(".bases-audio-inline audio, .bases-audio-overlay audio").forEach((audio) => {
          if (audio !== audioPlayer) {
            audio.pause();
          }
        });
        document.querySelectorAll(".bases-audio-play-button").forEach((btn) => {
          if (btn !== playButton) {
            btn.innerHTML = playIcon;
          }
        });
        audioPlayer.play();
        playButton.innerHTML = pauseIcon;
        isPlaying = true;
      }
    });
    audioPlayer.addEventListener("ended", () => {
      playButton.innerHTML = playIcon;
      isPlaying = false;
    });
    const fileNameSpan = document.createElement("span");
    fileNameSpan.textContent = fileName;
    fileNameSpan.style.cssText = "font-size: 0.9em; color: var(--text-muted);";
    container.appendChild(audioPlayer);
    container.appendChild(playButton);
    container.appendChild(fileNameSpan);
    return container;
  }
};
